### ISSUE TITLE
Issues connecting to Epic via CLI

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2848]
- [ ] Using `login` multiple times with same profile causes `Error: {"error":"invalid_request","error_description":null}`
- [ ] Using `--fhir-url-path` not persisted, so you need to added it on all subsequent calls `--fhir-url-path api/FHIR/R4`
- [x] Trailing slash on `--fhir-urlpath` leads to double slashes
- [x] `--private-key-path` relative to home directory, not current working directory
- [ ] Use `fetchTokens` rather than request as appropriate
