### ISSUE TITLE
Boost coverage for `@medplum/expo-polyfills`

### ISSUE THREAD

**Issue by ThatOneBro** [medplum/medplum#3271]
We have tests for basic functionality but the tests can be significantly improved to make sure that the polyfills are really doing their job.

We should do two different version of the tests:
* One in the `web` (`jsdom`) environment to make sure the polyfills don't modify the existing environment.
* One in the `react-native` environment. This should assert before the polyfill is run, that the APIs don't exist. Then after running the polyfills, the APIs should exist, and function as expected.

## TODO:
- [ ] Add `jsdom` harness and test file, `index.browser.test.ts`?
- [ ] Add `web`-specific tests.
- [ ] Add tests for `react-native`, asserting that the APIs don't exist before running polyfill, and after they do.
- [ ] After this is done, we should remove `packages/expo-polyfills/**/*` from `Sonar`'s exclusions in the config.

**Comment by ThatOneBro** [comment]
More or less completed, code coverage could be boosted more but we've already removed the polyfills from `Sonar` exclusion and added tests for `React Native` environment.
