### ISSUE TITLE
Medplum Auth "On Behalf Of" header

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3892]
## Use Case
For use when a client is wrapping the Medplum API with their own API service.

On reach request, the client API service will: 
- Create a new `MedplumClient` object
- Use Basic Authentication
- Pass on a new header, `X-Medplum-On-Behalf-Of`, to specify the `ProjectMembership` that of the user they are logging in as. 

## Design Considerations
- Should only be available to `ClientApplications` with `admin` priviledges

## Tasks
- [ ] Server parses new header
- [ ] Add `meta.onBehalfOf` field for history tracking
- [ ] Docs on API passthrough

**Comment by anthonynunn30M** [comment]
As a note the project membership would have to be looked up presumingly by practitioner ID, it would seem easier for the client application to send the practitioner ID and the medplum server does the project membership lookup as I can see having to repeat the same "lookup" code across different services causing repetition of code.

**Comment by rahul1** [comment]
@codyebberson - one design question that came up with a user - would this require the user to currently be auth'ed in when using `On-behalf-of`? I would assume "yes", but wanted to double check

**Comment by codyebberson** [comment]
> one design question that came up with a user - would this require the user to currently be auth'ed in when using On-behalf-of? I would assume "yes", but wanted to double check

Yes, that is correct.  The request will require authentication as a user (human or `ClientApplication`) with "project admin" access.

I suspect the question is based on the desire to run Medplum as a purely backend service that is not exposed to the open internet, in which case you could assume that all requests are "trusted" and therefore don't need authentication.  That feature is not on the roadmap.

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/4740 and https://github.com/medplum/medplum/pull/4866
